export const plansData = [
  {
    id: 1,
    plan: 'Free',
    price: 0,
    period: 'month',
    description: 'The essential to provide your best work for clients.',
    features: ['10 Projects', 'Up to 10 subscribers', 'Advanced analytics'],
    buttonLabel: 'Current Plan',
    buttonStyle: 'default',
    active: true,
  },
  {
    id: 2,
    plan: 'Basic',
    price: 20,
    period: 'month',
    description: 'Ideal for growing needs who want more features.',
    features: ['100 Projects', 'Up to 50 subscribers', 'Advanced analytics', '24-hour support'],
    buttonLabel: 'Upgrade',
    buttonStyle: 'highlighted',
    active: false,
  },
  {
    id: 3,
    plan: 'Advanced',
    price: 50,
    period: 'month',
    description: 'Designed for power users and maximum functionality.',
    features: [
      '200 Projects',
      'Up to 50 subscribers',
      'Advanced analytics',
      '24-hour support',
      'Marketing Advisor',
    ],
    buttonLabel: 'Upgrade',
    buttonStyle: 'default',
    active: false,
  },
];
